"""Acquittal-risk scoring: feature extraction + LightGBM predictor.

The numerical score is computed here. The LLM narrative is generated by
src/ai/services/risk_scoring.py.
"""
from aranmanai.core.risk.features import FeatureVector, compute_features
from aranmanai.core.risk.predictor import RiskPredictor

__all__ = ["compute_features", "FeatureVector", "RiskPredictor"]
